language: cpp

os:
  - linux
  # - osx

compiler:
  - g++
  # - clang

branches:
    only:
        - master
sudo: true
addons:
    apt:
        sources:
            - kubuntu-backports
        packages:
            - cmake

env:
  - TEST_DIR="2 - GUI and Draw simple graphics"
  - TEST_DIR="3 - Draw line"
  - TEST_DIR="4 - Transformation"
  - TEST_DIR="5 - Camera"
  - TEST_DIR="6 - Lights and Shading"
  - TEST_DIR="7 - Shadowing Mapping"
  - TEST_DIR="8 - Bezier Curve"


before_install:
  - sudo apt-get install libgl1-mesa-dev xorg-dev libglu1-mesa-dev libx11-dev

script: 
  - cd "$TEST_DIR"
  - mkdir build && cd build
  - cmake .. && make